#!/bin/bash -e

./scripts/test

if [ -d env ]; then
  source env/bin/activate
  if [ $2 ]; then
    gcloud preview app deploy \
      --project=$1 \
      --version=$2 \
      app.grow-prod.yaml
  elif [ $1 ]; then
    gcloud preview app deploy \
      --project=$1 \
      --version=auto \
      app.grow-prod.yaml
  else
    echo "Usage: ./scripts/deploy <project>"
    exit 1
  fi
  deactivate
else
  echo 'Run ./scripts/setup first.'
  exit 1
fi

