#!/bin/bash -e

./scripts/test

if [ -d env ]; then
  source env/bin/activate
  if [ $2 ]; then
    gcloud preview app deploy \
      --project=$1 \
      --version=$2 \
      --env_vars=JETWAY_CONFIG=config/jetway.grow-prod.yaml \
      app.yaml
  elif [ $1]; then
    gcloud preview app deploy \
      --project=$1 \
      --version=auto \
      --env_vars=JETWAY_CONFIG=config/jetway.grow-prod.yaml \
      app.yaml
  else
    gcloud preview app deploy app.yaml
  fi
  deactivate
else
  echo 'Run ./scripts/setup first.'
  exit 1
fi

