#!/bin/bash

pip --version > /dev/null || {
  echo "pip not installed. Installing..."
  sudo easy_install pip
}

virtualenv --version > /dev/null || {
  echo "virtualenv not installed. Installing..."
  sudo pip install virtualenv
}

gaenv -h > /dev/null || {
  echo "gaenv not installed. Installing..."
  sudo pip install gaenv
}

node --version > /dev/null || {
  echo "node not installed. Install from: http://nodejs.org/"
  exit 1
}

virtualenv env
source env/bin/activate
pip install -r requirements.txt
npm install
./node_modules/.bin/bower install
gaenv --lib lib --no-import
deactivate
